Resources:
  engineRoomTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "${self:custom.env.engineRoomTableName}"
      AttributeDefinitions:
        -
          AttributeName: playerId
          AttributeType: S
        -
          AttributeName: gameId
          AttributeType: S
        -
          AttributeName: nickName
          AttributeType: S
      KeySchema:
        -
          AttributeName: playerId
          KeyType: HASH
        -
          AttributeName: gameId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
      - IndexName: game-player-index # players by game
        KeySchema:
        - AttributeName: gameId
          KeyType: HASH
        - AttributeName: nickName
          KeyType: RANGE
        Projection:
          ProjectionType: ALL